[package]
name = "userboot"
version = "0.1.0"
authors = ["Isaac Woods"]
edition = "2018"

[dependencies]
libmessage = { path = "../libmessage" }

[profile.dev]
debug = false
panic = "abort"

[profile.release]
panic = "abort"
