[package]
name = "kernel_x86_64"
version = "0.1.0"
authors = ["Isaac Woods"]
edition = "2018"

[dependencies]
rlibc = "1"
kernel = { path = "../" }
hal = { path = "../hal" }
hal_x86_64 = { path = "../hal_x86_64" }
spin = "0.9.2"
log = "0.4"
bit_field = "0.10"
acpi = { path = "../../lib/acpi/acpi" }
aml = { path = "../../lib/acpi/aml" }
pebble_util = { path = "../../lib/pebble_util" }
gfxconsole = { path = "../../lib/gfxconsole" }
pci_types = { path = "../../lib/pci_types" }

[features]
qemu_exit = ["hal_x86_64/qemu"]
