[package]
name = "efiloader"
version = "0.1.0"
authors = ["Isaac Woods"]
edition = "2018"

[dependencies]
log = "0.4"
uefi = { path = "../../lib/uefi-rs", features = ["logger"] }
boot_info = { path = "../boot_info" }
