[package]
name = "efiloader"
version = "0.1.0"
authors = ["Isaac Woods"]
edition = "2018"

[dependencies]
log = "0.4"
uefi = { path = "../../lib/uefi-rs", features = ["logger"] }
ucs2 = { path = "../../lib/ucs2-rs" }
boot_info = { path = "../boot_info" }
mer = { path = "../../lib/mer" }
x86_64 = { path = "../../lib/x86_64" }
