language: rust
sudo: required
rust:
  - nightly

git:
  depth: 5

install:
  - sudo apt-get install mtools
  - sudo apt-get install qemu
  - rustup component add rust-src
  - cargo install cargo-xbuild
  - cargo install mdbook

script:
  - make
  - make test
  - make site
  - qemu-system-x86_64 --version
  - qemu-system-x86_64 -cpu ?
  - KERNEL_FLAGS='--features qemu_exit' make qemu-no-kvm

branches:
  only:
    - staging
    - trying
    - master

notifications:
  email: false

deploy:
  local-dir: pages
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
