language: rust
sudo: required
rust:
  - nightly

git:
  depth: 5

install:
  - rustup component add rust-src
  - cargo install cargo-xbuild

script:
  - make

branches:
  only:
    - staging
    - trying
    - master

notifications:
  email: false
