platform = "x64"

[x64]
release = false
user_tasks = [
    "platform_bus user/platform_bus",
    "pci_bus user/pci_bus",
    "usb_bus_xhci user/usb_bus_xhci",
    "simple_fb user/simple_fb",
    "echo user/echo",
]

[riscv]
# The release profile is heavily recommended for software-emulated targets to achieve reasonable speeds
release = true
