platform = "rv64_virt"

[x64]
release = false
user_tasks = [
    "platform_bus user/platform_bus",
    "pci_bus user/pci_bus",
    "usb_bus_xhci user/usb_bus_xhci",
    "simple_fb user/simple_fb",
    "echo user/echo",
]

[rv64_virt]
# The release profile is heavily recommended for software-emulated targets to achieve reasonable speeds
release = true
user_tasks = [
    "hello_world user/hello_world",
    "platform_bus user/platform_bus",
]

[mq_pro]
release = true
