platform = "rv64_virt"

[x64]
release = false
user_tasks = [
    "platform_bus user/platform_bus",
    # "usb_bus_xhci user/usb_bus_xhci",
    "simple_fb user/simple_fb",
    "echo user/echo",
]

[rv64_virt]
# The release profile is heavily recommended for software-emulated targets to achieve reasonable speeds
release = true
user_tasks = [
    "service_host user/service_host",
    "hello_world user/hello_world",
    "platform_bus user/platform_bus",
    "usb_bus_ehci user/usb_bus_ehci",
    "usb_hid user/usb_hid",
    "virtio_gpu user/virtio_gpu",
    "fb_console user/fb_console",
]
# Useful values: `virtio_*`, `usb_ehci_*`, `usb_packet_*`, `usb_*`
qemu_trace = ""

[mq_pro]
release = true
user_tasks = [
    "hello_world user/hello_world",
    "platform_bus user/platform_bus",
]

[uconsole]
release = true
