[package]
name = "simple_fb"
version = "0.1.0"
authors = ["Isaac Woods"]
edition = "2021"

[dependencies]
std = { path = "../../lib/std" }
log = "0.4"
gfxconsole = { path = "../../lib/gfxconsole" }
ptah = { path = "../../lib/ptah" }
