[package]
name = "kernel"
version = "0.1.0"
authors = ["Isaac Woods"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
cfg-if = "0.1"
bitflags = "1"
bit_field = "0.9"
num-traits = { version = "0.2", default-features = false }
log = { version = "0.4", default-features = false }
spin = "0.4"
x86_64 = { path = "../x86_64", optional = true }

[features]
arch_x86_64 = ["x86_64"]
tuning-fast_ctlz = []
