[package]
name = "kernel"
version = "0.1.0"
authors = ["Isaac Woods"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
hal = { path = "hal" }
hal_x86_64 = { path = "hal_x86_64", features = ["kernel"], optional = true }
pebble_util = { path = "../lib/pebble_util", features = ["has_alloc"] }
cfg-if = "0.1"
bitflags = "1"
bit_field = "0.10"
spin = "0.4"
log = { version = "0.4", default-features = false }
libpebble = { path = "../lib/libpebble" }

[features]
arch_x86_64 = ["hal_x86_64"]

[workspace]
members = ["efiloader", "hal", "hal_x86_64"]
