[package]
name = "kernel"
version = "0.1.0"
authors = ["Isaac Woods"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
cfg-if = "0.1"
bitflags = "1"
bit_field = "0.9"
spin = "0.4"
log = { version = "0.4", default-features = false }
x86_64 = { path = "../x86_64", optional = true }
acpi = { path = "../acpi", optional = true, features = ["debug_parser"] }
num = { version = "0.2", default-features = false }

[features]
arch_x86_64 = ["x86_64", "acpi"]
tuning-fast_ctlz = []
