[package]
name = "kernel"
version = "0.1.0"
authors = ["Isaac Woods"]
edition = "2018"

[dependencies]
hal = { path = "hal" }
pebble_util = { path = "../lib/pebble_util", features = ["has_alloc"] }
cfg-if = "0.1"
bitflags = "1"
bit_field = "0.10"
spin = "0.9.2"
log = { version = "0.4", default-features = false }
poplar = { path = "../lib/poplar" }
ptah = { path = "../lib/ptah" }
pci_types = "0.2"

[patch.crates-io]
pci_types = { path = "../lib/pci_types" }

[workspace]
members = ["efiloader", "hal", "hal_x86_64", "hal_arm64", "kernel_x86_64", "kernel_rpi4"]
