[package]
name = "seed"
version = "0.1.0"
authors = ["Isaac Woods"]
edition = "2021"

[dependencies]
hal = { path = "../lib/hal" }
heapless = "0.7.16"

[workspace]
members = ["seed_uefi", "seed_riscv", "d1_boot0"]
