[package]
name = "seed_riscv"
version = "0.1.0"
authors = ["Isaac Woods"]
edition = "2021"

[dependencies]
hal = { path = "../../lib/hal/" }
hal_riscv = { path = "../../lib/hal_riscv/" }
poplar_util = { path = "../../lib/poplar_util/" }
spinning_top = "0.2.4"
fdt = "0.1.3"
tracing = { git = "https://github.com/tokio-rs/tracing", default-features = false }
tracing-core = { git = "https://github.com/tokio-rs/tracing", default-features = false }
