[package]
name = "bootloader"
version = "0.1.0"
authors = ["Isaac Woods"]
edition = "2018"

[dependencies]
fixedvec = "0.2"

[profile.release]
debug = true
lto = true

[package.metadata.cargo-xbuild]
memcpy = true
