[package]
name = "bootloader"
version = "0.1.0"
authors = ["Isaac Woods"]
edition = "2018"

[dependencies]
fixedvec = "0.2"
bitflags = "1"
mer = "0.2"
x86_64 = { path = "../x86_64" }

[profile.release]
debug = true
lto = true

[package.metadata.cargo-xbuild]
memcpy = true
