[workspace]
members = ["simple_fb", "echo", "platform_bus", "pci_bus", "usb_bus_xhci", "test_tls", "test_pf", "test1", "test2",
"tests/test_syscalls"]

[profile.dev]
debug = false
panic = "abort"

[profile.release]
panic = "abort"
