name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
      
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        default: true
        profile: minimal
        components: rust-src
        
    - name: Install dependencies
      run: |
        sudo apt-get install mtools
        sudo apt-get install qemu
        
    - name: Build
      run: cargo xtask dist --kernel_features qemu_exit
      
    # TODO: run tests
    # - name: Run tests
    #   run: make test

    - name: Emulate
      run: |
        qemu-system-x86_64 --version
        cargo xtask qemu --kernel_features qemu_exit
