name: Deploy site

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: riscv64imac-unknown-none-elf
        default: true
        profile: minimal

    - name: Install dependencies
      run: |
        cargo install mdbook

      # This is a hack to get it building. TODO: address properly
    - name: Generate rustdoc documentation
      run: |
        RUSTDOCFLAGS="-Zunstable-options --enable-index-page" \
        cargo doc \
          --all-features \
          --target-dir pages \
          --manifest-path kernel/kernel_riscv/Cargo.toml \
          --target riscv64imac-unknown-none-elf \
          --document-private-items
        mv site/* pages/

    - name: Generate book
      run: |
        cd book && mdbook build

    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: pages
